<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
	    <key>fileTypes</key>
	    <array>
		    <string>dat</string>
        </array>
	    <key>name</key>
	    <string>Torchlight DAT</string>
	    <key>patterns</key>
        <array>
            <dict>
                <key>begin</key>
                <string>\s*(\[)(UNIT|TEXTURE_OVERRIDE_LIST|INVENTORY|EQUIPMENT)(\])</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.begin</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.end</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>\s*(\[\/)(UNIT|TEXTURE_OVERRIDE_LIST|INVENTORY|EQUIPMENT)(\])</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.begin</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.end</string>
                    </dict>
                </dict>
        	    <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>$self</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\s*(&lt;)(STRING)(&gt;)(\w+)?(:)?(.+)?$</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.begin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.end</string>
                            </dict>
                            <key>4</key>
                            <dict>
                                <key>name</key>
                                <string>variable.other</string>
                            </dict>
                            <key>5</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag</string>
                            </dict>
                            <key>6</key>
                            <dict>
                                <key>name</key>
                                <string>string.unquoted</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\s*(&lt;)(FLOAT)(&gt;)(\w+)?(:)?(\d+\.*\d*)?([^0-9.]+.*)?$</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.begin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.end</string>
                            </dict>
                            <key>4</key>
                            <dict>
                                <key>name</key>
                                <string>variable.other</string>
                            </dict>
                            <key>5</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag</string>
                            </dict>
                            <key>6</key>
                            <dict>
                                <key>name</key>
                                <string>constant.numeric</string>
                            </dict>
                            <key>7</key>
                            <dict>
                                <key>name</key>
                                <string>invalid</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\s*(&lt;)(INTEGER)(&gt;)(\w+)?(:)?(\d+)?(\D+.*)?$</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.begin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.end</string>
                            </dict>
                            <key>4</key>
                            <dict>
                                <key>name</key>
                                <string>variable.other</string>
                            </dict>
                            <key>5</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag</string>
                            </dict>
                            <key>6</key>
                            <dict>
                                <key>name</key>
                                <string>constant.numeric</string>
                            </dict>
                            <key>7</key>
                            <dict>
                                <key>name</key>
                                <string>invalid</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\s*(&lt;)(BOOL)(&gt;)(\w+)?(:)?(true|false)?(.*)?$</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.begin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.end</string>
                            </dict>
                            <key>4</key>
                            <dict>
                                <key>name</key>
                                <string>variable.other</string>
                            </dict>
                            <key>5</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag</string>
                            </dict>
                            <key>6</key>
                            <dict>
                                <key>name</key>
                                <string>constant.language</string>
                            </dict>
                            <key>7</key>
                            <dict>
                                <key>name</key>
                                <string>invalid</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\s*(&lt;)(TRANSLATE)(&gt;)(\w+)?(:)?(.*)?$</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.begin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.end</string>
                            </dict>
                            <key>4</key>
                            <dict>
                                <key>name</key>
                                <string>variable.other</string>
                            </dict>
                            <key>5</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag</string>
                            </dict>
                            <key>6</key>
                            <dict>
                                <key>name</key>
                                <string>string.unquoted</string>
                            </dict>
                        </dict>
                    </dict>
                </array>
            </dict>
        </array>
	    <key>scopeName</key>
	    <string>source.tldat</string>
	    <key>uuid</key>
	    <string>DAD2D1A1-1460-4F3A-9B03-C25E4EA85E5B</string>
    </dict>
</plist>